xaplus:
  serverId: "ledger-1"
  transactionsTimeoutInSeconds: 10
  recoveryTimeoutInSeconds: 30
server:
  port: 8001
db:
  url: jdbc:postgresql://127.0.0.1:10001/ledger
  user: ledger
  password: ledger