xaplus:
  serverId: "ledger-2"
  transactionsTimeoutInSeconds: 10
  recoveryTimeoutInSeconds: 30
  recoveryPeriodInSeconds: 30
server:
  port: 8002
db:
  url: jdbc:postgresql://127.0.0.1:10002/ledger
  user: ledger
  password: ledger