xaplus:
  serverId: "ledger-3"
  transactionsTimeoutInSeconds: 10
  recoveryTimeoutInSeconds: 30
  recoveryPeriodInSeconds: 30
server:
  port: 10003
db:
  url: jdbc:postgresql://127.0.0.1:20003/ledger
  user: ledger
  password: ledger
ledger-1:
  hostname: 127.0.0.1
  port: 10001
ledger-2:
  hostname: 127.0.0.1
  port: 10002
ledger-3:
  hostname: 127.0.0.1
  port: 10003