xaplus:
  serverId: "ledger-3"
  transactionsTimeoutInSeconds: 10
  recoveryTimeoutInSeconds: 30
server:
  port: 8003
db:
  url: jdbc:postgresql://127.0.0.1:10003/ledger
  user: ledger
  password: ledger